services:
  - type: static
    name: fitmat-frontend
    env: node
    region: oregon
    repo: https://github.com/vildashnetwork/fitmat-campus-hub
    branch: main
    root: "" # empty because package.json is at project root
    buildCommand: "npm ci && npm run build"
    publishPath: "dist"
